name: Run CI for project
on:
 #Schedule pipeline run 30minutes / pipeline
    # schedule:
    #   - cron: "0/30 * * * *"
    repository_dispatch:
    workflow_dispatch:
    push:

          
jobs: 

  Deployment-project:
        if: github.ref == 'refs/heads/main'
        needs: Build-and-upload-docker-image
        runs-on:  ubuntu-latest 

        steps:
        - name: Clone repository code
          uses: actions/checkout@v2

        - name: Install kubectl
          uses: azure/setup-kubectl@v1
          with:
             version: 'v1.21.3'
          id: install

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Update kube config
          run: aws eks update-kubeconfig --name demo-github-action --region us-east-1

        - name: Deploy image to Amazon EKS
          run: |
            kubectl apply -f eks/secret.yaml
            kubectl apply -f eks/my-app.yaml
            kubectl apply -f eks/ingress.yaml 