name: build project
on:
    push:
      branches: [main]

jobs: 
      docker:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2

          - name: login docker hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME}}
                password: ${{ secrets.DOCKER_HUB_PASSWORD}}
          
          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v1
            id: buildx

          - name: Build and push Docker Image
            uses: docker/build-push-action@v1
            id: docker_build
            with:
              context: ./
              file: ./Dockerfile
              builder: ${{steps.buildx.output.name}}
              push: true
              tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-petclinic

          - name: Verify
            run: echo ${{steps.docker_build.output.digest }}    

            
