name: build project
on:
    push:
      branches: [main]

jobs: 
      docker:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2

          - name: Setup java
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'adopt'   

          - name: Build artifacts
            run: |
              mvn -N wrapper:wrapper -Dmaven=3.5.2
              ./mvnw spring-boot:build-image

          - name: Upload artifacts
            run: |
               mkdir staging && cp target/*.jar staging


          # - name: Login docker hub
          #   uses: docker/login-action@v1
          #   with:
          #       username: ${{ secrets.DOCKER_HUB_USERNAME}}
          #       password: ${{ secrets.DOCKER_HUB_PASSWORD}}
          
          # - name: Setup docker buildx
          #   uses: docker/setup-buildx-action@v1
          #   id: buildx

          # - name: Build and push Docker Image
          #   uses: docker/build-push-action@v1
          #   id: docker_build
          #   with:
          #     context: ./
          #     file: ./Dockerfile
          #     builder: ${{steps.buildx.output.name}}
          #     push: true
          #     tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-petclinic

          # - name: Verify
          #   run: echo ${{steps.docker_build.output.digest }}    

            
