name: build project
on:
 #Schedule pipeline run 30minutes / pipeline
    # schedule:
    #   - cron: "0/30 * * * *"
    repository_dispatch:
    workflow_dispatch:
    push:
      branches:
        - "developer"
env:
    repo: 00375877633/latest    
    snapshot: spring-petclinic-2.6.0-SNAPSHOT.jar   
    projectKey: tuanngociuit98_spring-petclinic
          
jobs: 
      Build-snapshots:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code 
            uses: actions/checkout@v2

          - name: Setup java
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'adopt'     
            
          - name: Build snapshots for web
            run: |
             chmod +x mvnw
              mvn -N wrapper:wrapper -Dmaven=3.5.2
              ./mvnw spring-boot:build-image

          - name: Upload snapshots
            uses: actions/upload-artifact@v3
            with:
              name: my-snapshot
              path: target/$snapshot
              required: true

          - name: Check code quality
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            run: |
                mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$projectKey 
          
          - name: Upload Dockerfile 
            uses: actions/upload-artifact@v3   
            with:
              name: Dockerfile
              path: Dockerfile
              required: true 
              
          - name: Cache SonarCloud packages
            uses: actions/cache@v1
            with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar

          - name: Cache building dependencies
            uses:  actions/cache@v2
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                  ${{ runner.os }}-maven-

          

             
          
            

     
               
          
                 
