name: build project
on:
    push:
      branches: [main]
    
jobs: 
      Build-artifacts:

        runs-on: ubuntu-latest
        steps:
          - name: Checkout code 
            uses: actions/checkout@v2

          - name: Setup java
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'adopt'   

          - name: Build artifacts
            run: |
             chmod +x mvnw
              mvn -N wrapper:wrapper -Dmaven=3.5.2
              ./mvnw spring-boot:build-image

          - name: Download artifacts product
            uses: actions/download-artifact@v3
            with:
              name: website artifacts

          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v2
            id: buildx

          - name: Login docker hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME}}
                password: ${{ secrets.DOCKER_HUB_PASSWORD}}

          - name: Build and push Docker Image
            uses: docker/build-push-action@v2
            id: docker_build
            with:
              context: ./
              file: ./Dockerfile
              builder: ${{steps.buildx.output.name}}
              push: true
              tags: ${{secrets.DOCKER_HUB_USERNAME}}/latest

          - name: Verify
            run: echo ${{steps.docker_build.output.digest }}  
                

            

            
