name: Run CI for project
on:
 #Schedule pipeline run 30minutes / pipeline
    # schedule:
    #   - cron: "0/30 * * * *"
    repository_dispatch:
    workflow_dispatch:
    pull_request:
      types: [closed]
env:
    repo: 00375877633/latest    
    snapshot: spring-petclinic-2.6.0-SNAPSHOT.jar   
    projectKey: tuanngociuit98_spring-petclinic
          
jobs: 
      Build-snapshots:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code 
            uses: actions/checkout@v2


          - name: Setup java
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'adopt'     
            
          - name: Build snapshots for web
            run: |
             chmod +x mvnw
              mvn -N wrapper:wrapper -Dmaven=3.5.2
              ./mvnw spring-boot:build-image -Dcheckstyle.skip

          - name: Check code quality
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            run: |
                mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$projectKey -Dcheckstyle.skip   

          - name: Upload snapshots
            uses: actions/upload-artifact@v3
            with:
              name: my-snapshot
              path: target/$snapshot
              required: true
          
          - name: Upload Dockerfile 
            uses: actions/upload-artifact@v3   
            with:
              name: Dockerfile
              path: Dockerfile
              required: true 

          - name: Cache building dependencies
            uses:  actions/cache@v2
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                  ${{ runner.os }}-maven-

          - name: Cache SonarCloud packages
            uses: actions/cache@v1
            with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar  
          
      Build-and-upload-docker-image:
        if: github.ref == 'refs/heads/main'
        runs-on:  ubuntu-latest
        needs: Build-snapshots
        steps:  

        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v2
          id: buildx

        - name: Download snapshots
          uses: actions/download-artifact@v2
          with:
            name: my-snapshot
        - name: Download Dockerfile
          uses: actions/download-artifact@v2
          with:
            name: Dockerfile
        
        - run: |
            ls -l

        - name: Login docker hub
          uses: docker/login-action@v1
          with:
                username: ${{ secrets.DOCKER_HUB_USERNAME}}
                password: ${{ secrets.DOCKER_HUB_PASSWORD}}

        - name: Build and push Docker Image
          run: |
            docker build -t spring-petclinic .
            docker tag spring-petclinic:latest $repo
            docker push $repo
            

    
          
       
            


     
               
          
                 
