name: Continuos deployment for project
on:
    workflow_run:
      workflows: ["Run CI for project"]
      types:
        - "completed"
    workflow_dispatch:
       
jobs: 

  Deployment-project:              
        runs-on:  ubuntu-latest 
        steps:
        - name: Clone repository code
          uses: actions/checkout@v2

        - name: Install kubectl
          uses: azure/setup-kubectl@v2.0
          with:
             version: 'v1.21.3'
          id: install

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Update kube configure
          run: aws eks update-kubeconfig --name k8s-demo --region us-east-1

        - name: Deploy image to Amazon EKS
          run: |
            kubectl apply -f eks/secret.yaml
            kubectl apply -f eks/my-app.yaml
            kubectl apply -f eks/my-app-service.yaml 

        - name: Waiting for Deployment
          run: |
            sleep 120s
          shell: bash      

  Check-health-URL:
       needs: Deployment-project 
       
       runs-on: ubuntu-latest 
       outputs:
         http_code: ${{ steps.healthcheck.outputs.http_code }}
       steps:  
        - name: healthcheck URL
          id: healthcheck
          run: |       
            echo "::set-output name=http_code::$(curl -o -I -L -s -w "%{http_code}" ae9786127e4394b28b06925303ad774d-1000177221.us-east-1.elb.amazonaws.com)"
            

  Notify-healthcheck :
      runs-on: ubuntu-latest
      needs: Check-health-URL
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      steps:
        - name: Run http code
          run: echo ${{needs.Check-health-URL.outputs.http_code}}
        - name: Notify deployment success
          if: ${{needs.Check-health-URL.outputs.http_code == 200}} 
          uses: act10ns/slack@v1
          with: 
           status: build successfull
           channel: '#ci'
           message: Deploy  Successfully
        
        - name: Notify deployment fail
          if: ${{needs.Check-health-URL.outputs.http_code != 200}} 
          uses: act10ns/slack@v1
          with: 
           status: Deployment failed
           channel: '#ci'
           message: Deployment fail,  Please rollback k8s

     
          