name: Run CD for project
on:
 #Schedule pipeline run 30minutes / pipeline
    # schedule:
    #   - cron: "0/30 * * * *"
    repository_dispatch:
    workflow_dispatch:
    push:

          
jobs: 

  # Deployment-project:
              
  #       runs-on:  ubuntu-latest 

  #       steps:
  #       - name: Clone repository code
  #         uses: actions/checkout@v2

  #       - name: Install kubectl
  #         uses: azure/setup-kubectl@v2.0
  #         with:
  #            version: 'v1.21.3'
  #         id: install

  #       - name: Configure AWS credentials
  #         uses: aws-actions/configure-aws-credentials@v1
  #         with:
  #           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           aws-region: us-east-1

  #       - name: Update kube configure
  #         run: aws eks update-kubeconfig --name k8s-demo --region us-east-1

  #       - name: Deploy image to Amazon EKS
  #         run: |
  #           kubectl apply -f eks/secret.yaml
  #           kubectl apply -f eks/my-app.yaml
  #           kubectl apply -f eks/my-app-service.yaml 

  Check-health-URL:
      #  needs: Deployment-project 
       
       runs-on: ubuntu-latest 
       outputs:
         http_code: ${{ steps.healthcheck.outputs.http_code }}
       steps:  
        - name: healthcheck URL
          id: healthcheck
          run: |
            http_code=$(curl -o -I -L -s -w "%{http_code}" google.com)        
            echo `::set-output name=http_code::$http_code`
            

  Output-healthcheck :
      runs-on: ubuntu-latest
      needs: Check-health-URL
      steps:
        - name: Output
          run: |
            echo ${{needs.Check-health-URL.outputs.http_code}}


     
          